import { useState } from "react";
import Navbar from "../Components/Navbar";
import { ChevronDown, ChevronUp, Shield, Eye, Lock, Database, Users, Globe, Scale, Mail, Phone, MapPin } from "lucide-react";

export default function PrivacyPolicy() {
  const [openSection, setOpenSection] = useState(null);

  const toggleSection = (index) => {
    setOpenSection(openSection === index ? null : index);
  };

  const sections = [
    {
      title: "General",
      icon: <Shield className="w-5 h-5" />,
      content: [
        "This Privacy Policy is to provide you ('You' or 'Your' or 'User' or 'Users') information of the data usage by our website casualsbyarchanasolanki.in",
        "The term User/User(s) means any individual or entity which uses, accesses or browses Casuals by Archana Solanki and/or purchases Products from Casuals by Archana Solanki. (Hereinafter referred to as ‘We’ or ‘Us’ or ‘Our’).",
        "You are required to read this Privacy Policy carefully since Your use of Casuals by Archana Solanki(hereinafter referred to as ‘Website’ or ‘Site’) implies knowledge, understanding and acceptance of all terms of this Privacy Policy.",
        "In this Privacy Policy, We set out the types of information that We may collect, the purpose of collection of the information, how We collect, use, disclose, transfer and store Your information so that you can make an informed decision in relation to the sharing of your personal information with Us."
      ]
    },
    {
      title: "Applicability",
      icon: <Globe className="w-5 h-5" />,
      content: [
        "You may be able to access or browse Casuals by Archana Solanki from outside the geographical territories of the Republic of India, however, please note that the Products listed the site are not offered for sale outside the geographical territories of the Republic of India.",
        "Your Information will primarily be collected, stored and processed in India and will be governed by the applicable laws (including data protection and privacy laws) that are different from those that apply in the country in which you are located.",
        "This document is an electronic record and is governed by the provisions of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
        "You may be asked to provide your information anytime you visit, access, use or browse our site. We may share information and use it consistent with the provisions of this Privacy Policy. We may also combine it with other information to provide and improve our Products, services, content and advertising. Please familiarize yourself with our Privacy Policy. If you do not agree with any provisions of the Terms or this Privacy Policy, we advise you to not use or access Casuals by Archana Solanki."
      ]
    },
    {
      title: "Type of Information Collected",
      icon: <Database className="w-5 h-5" />,
      content: [
        "This Privacy Policy sets out the type of information collected from the Users. You may at any time withdraw your consent for collection and use of your Information including Personal Information or Sensitive Personal Data/ Information. However, please note that if you withdraw your consent, we may no longer be able to provide you with the corresponding service for which you have withdrawn your consent. It is hereby clarified that your decision to withdraw your consent will not affect the processing of Information based on your previous consent prior to the withdrawal.",
        "When you use our Site, We collect and store information shared by You. Our primary goal in doing so is for the purposes of providing our services. In general, the User can browse the Site without revealing any personal information about Yourself. However, to fully use our Site, You will need to signup, where You may be required to provide Us with Your name, contact number, email id, password, billing information, shipping information, bank account details and other personal information as indicated in the forms throughout the Site. You always have the option to not provide information by choosing not to use a particular service or feature on the Site.",
        "We may automatically track certain information like the URL that You just came from (whether this URL is on our Site or not), which URL you go to next (whether this URL is on our Site or not), your computer browser information, and your IP address, based upon your activities on our Site. ",
        "You agree that We may also collect information such as location as and when suitable to us.",
        "NOTE: You agree to provide information which shall be true, correct, up to date and accurate."
      ]
    },
    {
      title: "Usage of Collected Information",
      icon: <Eye className="w-5 h-5" />,
      content: [
        "We may collect, use or process your information including Personal Information and Sensitive Personal Data/Information for the following purposes:",
        "• For creating and giving you access to your registered account on Casuals by Archana Solanki",
        "• To validate and process your request for the provision of Products or accessing of Casuals by Archana Solanki",
        "• To assist merchants to handle and fulfil your orders",
        "• To develop, deliver, process and improve our Products, services, content in order to personalize and improve your experience",
        "• To inform you about our Products, services, offers, discounts, updates, promotional initiatives, upcoming events, that may be of your interest, including providing you information in relation to your order confirmations, invoices, delivery status, technical notices, security alerts, etc.",
        "• For our internal business analytical and research purposes such as auditing, data analysis and research to improve our Products, services and customer communications",
        "• To meet any legal or regulatory requirement or comply with a request from any governmental or judicial authority",
        "• To provide you with recommendation about Products you may be interested in",
        "• To provide you with marketing communications and advertising that we believe may be of interest for you",
        "• To resolve any request, dispute, grievance or complaint raised by you in relation to your use of Casuals by Archana Solanki",
        "• To detect or monitor any fraudulent or illegal activity on our website"
      ]
    },
    {
      title: "Disclosure of Information",
      icon: <Users className="w-5 h-5" />,
      content: [
        "We may from time to time be required to disclose the Information collected from you to our trusted third-party service providers who assist us in order to facilitate the provision of certain services in relation to your purchase of Products on our Site.",
        "We ensure that such third-party service providers are bound by reasonable confidentiality obligations and/or use, maintain and follow generally accepted industry and security standards commensurate with the security standards set forth in this Privacy Policy with respect to such Information and are also compliant with applicable laws.",
        "To the extent permitted under the applicable laws, we may also disclose your Information with external organization or individuals if we have reasons to believe that the access, use, preservation or disclosure of the Information is reasonably necessary.",
        "We may also disclose or transfer your Information to any third party as a part of reorganization or a sale of the assets, division or transfer of a part or whole of us. We shall ensure that the third-party to whom we transfer or sell our assets have appropriate confidentiality and security measures, at least as protective as those described in this Privacy Policy and as per applicable laws.",
        "A third-party payment gateway provider may be required to collect certain financial information from you including, but not restricted to, your credit/debit card number or your bank account details.",
        "All Financial Information collected from you by such third-party payment gateway providers will be used only for billing and payment processes. The Financial Information collected from you is transacted through secure digital platforms of approved payment gateways which are under encryption, thereby complying with reasonably expected technology standards. The verification of the Financial Information shall be accomplished only by you through a process of authentication in which we shall have no role to play and hence, we shall bear no liability in relation to the same. We shall neither be liable nor responsible for any actions or inactions of third-party payment gateway providers or any breach of conditions, representations and warranties given by them. We shall also not be obligated to mediate or resolve any dispute or disagreement between you and such third-party payment gateway providers.",
        "You are strongly advised to exercise reasonable discretion while providing Personal Information or Financial Information and Sensitive Personal Data/Information while using the services given that the Internet is susceptible to security breaches."
      ]
    },
    {
      title: "Cooperation with Law & Governing Law",
      icon: <Scale className="w-5 h-5" />,
      content: [
        "We cooperate with law enforcement and regulatory inquiries, as well as other third parties to enforce laws, such as: intellectual property rights, fraud and other rights, to help protect users. Therefore, in response to a verified request by law enforcement or other government officials relating to a criminal investigation or alleged illegal activity, we can (and You hereby authorize Us to) disclose Your name, city, state, phone number, email address, User ID history, fraud complaints, and purchasing history without notice.",
        "The terms of this Privacy Policy shall be governed and construed in accordance with the laws of India without reference to any conflict of laws principles. You agree to the exclusive jurisdiction of the courts of Pune, Maharashtra for any dispute arising under or in connection with this Privacy Policy.",
      ]
    },
    {
      title: "Security",
      icon: <Lock className="w-5 h-5" />,
      content: [
        "Secure Server Software: When You place orders or access Your account information, We offer the use of a secure server. The secure socket layer (SSL) encrypts all information You put in before it is sent to Us.",
        "Furthermore, all of the customer data We collect is protected against unauthorized access. To prevent unauthorized access, maintain data accuracy, and ensure correct use of information.",
        "Privacy Guarantee: Any employee who violates our privacy and/or security policies is subject to disciplinary action, including possible termination and civil and/or criminal prosecution.",
        "Only those of our employees who need access to Your information in order to perform their duties are allowed such access."
      ]
    },
    {
      title: "Changes in Policy",
      icon: <Eye className="w-5 h-5" />,
      content: [
        "Your visit and any dispute over privacy is subject to this policy and the Terms and Conditions set out on the Website, including limitations on damages.",
        "We reserve the right to change the Terms and Conditions and this Privacy Policy, at any time. We will post any changes so that You are always aware of our policy.",
        "Unless stated otherwise, our current Privacy Policy applies to all information that We have about You and Your account."
      ]
    },
    {
      title: "User Rights",
      icon: <Shield className="w-5 h-5" />,
      content: [
        "You have control over your personal information.",
        "This means you can: Ask us for a copy of the data we hold about you, withdraw any consent you've previously given us."
      ]
    }
  ];

  return (
    <>
    <Navbar/>
    <div className="min-h-screen bg-white text-black pt-24">
      {/* Header */}
      <div className="bg-black text-white">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <div className="text-center">
            <div className="inline-flex items-center justify-center w-20 h-20 bg-white text-black rounded-full mb-6">
              <Shield className="w-10 h-10" />
            </div>
            <h1 className="text-5xl md:text-6xl font-light tracking-wide mb-4">
              PRIVACY POLICY
            </h1>
            <div className="w-24 h-px bg-white mx-auto mb-6"></div>
            <p className="text-lg font-light tracking-wider opacity-90">
              CASUALS BY ARCHANA SOLANKI
            </p>
            <p className="text-sm font-light opacity-70 mt-2">
              Your privacy is our priority
            </p>
          </div>
        </div>
      </div>

      {/* Introduction */}
      <div className="max-w-4xl mx-auto px-6 py-16">
        <div className="prose prose-lg max-w-none mb-12">
          <div className="bg-gray-50 p-8 border-l-4 border-black">
            <p className="text-lg leading-relaxed font-light mb-4">
              We are committed to protecting and respecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your personal information when you visit our website <strong>casualsbyarchanasolanki.in</strong>.
            </p>
            <p className="text-base leading-relaxed font-light opacity-80">
              By using our website, you consent to the data practices described in this policy. Please take the time to read this policy carefully to understand how we handle your information.
            </p>
          </div>
        </div>

        {/* Privacy at a Glance */}
        <div className="grid md:grid-cols-3 gap-6 mb-16">
          <div className="bg-white border border-gray-200 p-6 text-center hover:shadow-lg transition-shadow duration-300">
            <div className="w-12 h-12 bg-black text-white rounded-full flex items-center justify-center mx-auto mb-4">
              <Lock className="w-6 h-6" />
            </div>
            <h3 className="font-medium text-lg mb-2">Secure Collection</h3>
            <p className="text-gray-600 font-light">SSL encryption protects your data</p>
          </div>
          <div className="bg-white border border-gray-200 p-6 text-center hover:shadow-lg transition-shadow duration-300">
            <div className="w-12 h-12 bg-black text-white rounded-full flex items-center justify-center mx-auto mb-4">
              <Eye className="w-6 h-6" />
            </div>
            <h3 className="font-medium text-lg mb-2">Transparent Usage</h3>
            <p className="text-gray-600 font-light">Clear purpose for data collection</p>
          </div>
          <div className="bg-white border border-gray-200 p-6 text-center hover:shadow-lg transition-shadow duration-300">
            <div className="w-12 h-12 bg-black text-white rounded-full flex items-center justify-center mx-auto mb-4">
              <Shield className="w-6 h-6" />
            </div>
            <h3 className="font-medium text-lg mb-2">Your Control</h3>
            <p className="text-gray-600 font-light">Withdraw consent anytime</p>
          </div>
        </div>

        {/* Expandable Sections */}
        <div className="space-y-4">
          {sections.map((section, index) => (
            <div key={index} className="border border-gray-200 bg-white shadow-sm hover:shadow-md transition-shadow duration-300">
              <button
                onClick={() => toggleSection(index)}
                className="w-full px-8 py-6 flex items-center justify-between bg-white hover:bg-gray-50 transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-black focus:ring-inset"
              >
                <div className="flex items-center space-x-4">
                  <div className="p-2 bg-black text-white">
                    {section.icon}
                  </div>
                  <h3 className="text-xl font-light tracking-wide text-left">
                    SECTION {String.fromCharCode(65 + index)} - {section.title.toUpperCase()}
                  </h3>
                </div>
                <div className="flex-shrink-0">
                  {openSection === index ? (
                    <ChevronUp className="w-6 h-6 text-gray-600" />
                  ) : (
                    <ChevronDown className="w-6 h-6 text-gray-600" />
                  )}
                </div>
              </button>
              
              <div className={`overflow-hidden transition-all duration-300 ease-in-out ${
                openSection === index ? 'max-h-screen opacity-100' : 'max-h-0 opacity-0'
              }`}>
                <div className="px-8 pb-8">
                  <div className="pl-12 space-y-4">
                    {section.content.map((paragraph, pIndex) => (
                      <div key={pIndex}>
                        {paragraph.startsWith('NOTE:') ? (
                          <div className="bg-blue-50 border-l-4 border-blue-400 p-4 my-4">
                            <p className="text-blue-800 font-medium text-sm">
                              {paragraph}
                            </p>
                          </div>
                        ) : paragraph.startsWith('•') ? (
                          <div className="flex items-start space-x-3">
                            <div className="w-2 h-2 bg-black rounded-full mt-3 flex-shrink-0"></div>
                            <p className="text-gray-700 leading-relaxed font-light">
                              {paragraph.substring(2)}
                            </p>
                          </div>
                        ) : (
                          <p className="text-gray-700 leading-relaxed font-light">
                            {paragraph}
                          </p>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Data Types We Collect */}
        <div className="mt-16 bg-black text-white p-8">
          <h3 className="text-2xl font-light tracking-wide text-center mb-8">INFORMATION WE COLLECT</h3>
          
          <div className="grid md:grid-cols-2 gap-8">
            <div>
              <h4 className="text-lg font-medium mb-4 flex items-center">
                <Database className="w-5 h-5 mr-2" />
                Personal Information
              </h4>
              <ul className="space-y-2 text-sm font-light opacity-90">
                <li>• Full Name</li>
                <li>• Contact Number</li>
                <li>• Email Address</li>
                <li>• Billing & Shipping Address</li>
                <li>• Bank Account Details</li>
              </ul>
            </div>
            
            <div>
              <h4 className="text-lg font-medium mb-4 flex items-center">
                <Eye className="w-5 h-5 mr-2" />
                Automatic Information
              </h4>
              <ul className="space-y-2 text-sm font-light opacity-90">
                <li>• Browser Information</li>
                <li>• IP Address</li>
                <li>• URL Navigation</li>
                <li>• Location Data</li>
                <li>• Site Activity</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Security Measures */}
        <div className="mt-16 grid md:grid-cols-2 gap-8">
          <div className="bg-green-50 border border-green-200 p-6">
            <div className="flex items-center mb-4">
              <Lock className="w-6 h-6 text-green-600 mr-3" />
              <h4 className="text-lg font-medium text-green-800">Security Measures</h4>
            </div>
            <ul className="space-y-2 text-green-700 font-light">
              <li>• SSL encryption for data transmission</li>
              <li>• Secure server infrastructure</li>
              <li>• Access controls for employees</li>
              <li>• Regular security audits</li>
            </ul>
          </div>
          
          <div className="bg-blue-50 border border-blue-200 p-6">
            <div className="flex items-center mb-4">
              <Shield className="w-6 h-6 text-blue-600 mr-3" />
              <h4 className="text-lg font-medium text-blue-800">Your Rights</h4>
            </div>
            <ul className="space-y-2 text-blue-700 font-light">
              <li>• Access your personal data</li>
              <li>• Withdraw consent anytime</li>
              <li>• Request data correction</li>
              <li>• Control marketing communications</li>
            </ul>
          </div>
        </div>

        {/* Contact Information */}
        <div className="mt-16 bg-white border-2 border-black p-8">
          <h3 className="text-3xl font-light tracking-wide text-center mb-8">QUESTIONS? CONTACT US</h3>
          
          <div className="text-center space-y-4">
            <p className="text-lg font-light mb-6">
              In case you have any questions/queries about this Privacy Policy, please contact:
            </p>
            
            <div className="flex flex-col md:flex-row justify-center items-center space-y-4 md:space-y-0 md:space-x-8">
              <div className="flex items-center space-x-3">
                <Mail className="w-5 h-5" />
                <span className="font-light">casualsbyarchanasolanki@gmail.com</span>
              </div>
              <div className="flex items-center space-x-3">
                <Phone className="w-5 h-5" />
                <span className="font-light">+91 8788292204</span>
              </div>
            </div>
            
            <div className="mt-6 pt-6 border-t border-gray-200">
              <div className="flex items-center justify-center space-x-3">
                <MapPin className="w-5 h-5" />
                <span className="font-light">Governed by Laws of India | Jurisdiction: Pune, Maharashtra</span>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-16 text-center py-8 border-t border-gray-200">
          <p className="text-sm font-light opacity-70 mb-2">
            © 2024 Casuals by Archana Solanki. All rights reserved.
          </p>
          <p className="text-xs font-light opacity-50">
            This Privacy Policy is subject to change. Please review periodically for updates.
          </p>
        </div>
      </div>
    </div>
    </>
  );
}